# Generated by Django 2.0.7 on 2018-08-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='ailment_herb',
        ),
        migrations.AddField(
            model_name='herb',
            name='ailment_herbs',
            field=models.ManyToManyField(related_name='herb_ailments', to='users.Ailment'),
        ),
    ]
