# Generated by Django 2.0.7 on 2018-08-11 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180809_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herb_in_cart', to='users.Herb')),
                ('purchase_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_purchase', to='users.User')),
            ],
        ),
    ]
